export enum ScrapeRunStepStatus {
  PENDING = 'PENDING',
  NEXT = 'NEXT',
  RUNNING = 'RUNNING',
  RETRYING = 'RETRYING',
  COMPLETED = 'COMPLETED',
  COMPLETED_WITH_ERRORS = 'COMPLETED_WITH_ERRORS',
  SKIPPED = 'SKIPPED',
}
