export enum HomeType {
  APARTMENT = 'APARTMENT',
  CONDO = 'CONDO',
  LOT = 'LOT',
  MANUFACTURED = 'MANUFACTURED',
  MULTI_FAMILY = 'MULTI_FAMILY',
  SINGLE_FAMILY = 'SINGLE_FAMILY',
  TOWNHOUSE = 'TOWNHOUSE',
}
